run_newman:
	newman run --global-var id=1 --export-globals variables.json Global_Variables.postman_collection.json

run_newman_global_files:
	newman run --globals globalfile.json --export-globals variables.json Global_Variables.postman_collection.json