run_newman_csv:
	newman run collections/sck-shoping-mall-level2.postman_collection.json \
	-e env/sck-shoping-mall-dev.postman_environment.json \
	-d data/shoping-mall.csv

run_newman_json_dev:
	newman run collections/sck-shoping-mall-level2.postman_collection.json \
	-e env/sck-shoping-mall-dev.postman_environment.json \
	-d data/shoping-mall.json

run_newman_json_qa:
	newman run collections/sck-shoping-mall-level2.postman_collection.json \
	-e env/sck-shoping-mall-qa.postman_environment.json \
	-d data/shoping-mall.json